# -*- coding: utf-8 -*-
"""Wagon_Assignment_Anirudha.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-y-_RoE77r5Y8xXC-fG_dj-AWceTimle
"""

pip install opencv-python numpy fpdf

!pip install opencv-python moviepy ultralytics reportlab

from google.colab import drive
drive.mount('/content/drive')

!pip install gdown
!gdown --folder https://drive.google.com/drive/folders/13GaVu0IXX65M0WIsEH9OmkD9DlSyoXL2

import os
print(os.listdir("/content"))

video_folder = "/content/13GaVu0IXX65M0WIsEH9OmkD9DlSyoXL2"

!pip install moviepy

import os

# Correct path (case-sensitive!)
video_folder = "/content/Raw_video"

# List files in the folder
print(os.listdir(video_folder))

import os
print(os.listdir("/content"))

import os

# Correct path (case-sensitive!)
video_folder = "/content/Raw_video"

# List files in the folder
print(os.listdir(video_folder))

import os

# Change this to your Drive folder path
BASE_DIR = "/content/drive/MyDrive/Train_Assignment"

RAW_VIDEO = os.path.join(BASE_DIR, "DHN-wagon/Raw_video.mp4")
PROCESSED_DIR = os.path.join(BASE_DIR, "Processed_Video")
REPORT_DIR = os.path.join(BASE_DIR, "Final_Report")

os.makedirs(PROCESSED_DIR, exist_ok=True)
os.makedirs(REPORT_DIR, exist_ok=True)

from google.colab import drive
drive.mount('/content/drive')
# create Drive output folder path (change if needed)
!mkdir -p "/content/drive/MyDrive/Processed_Video"

# run in a code cell
!pip install --quiet opencv-python-headless moviepy ultralytics reportlab scipy

import os, cv2
from pathlib import Path
from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from datetime import datetime

# ---------- config ----------
RAW_DIR = "/content/Raw_video"      # input folder with videos
OUTPUT_DIR = "/content/Processed"   # output folder
os.makedirs(OUTPUT_DIR, exist_ok=True)

FRAME_EVERY = 30   # extract every 30th frame
N_FRAMES_PDF = 6   # max frames to show in PDF

# ---------- helper: extract frames ----------
def extract_frames(video_path, out_folder, step=30):
    cap = cv2.VideoCapture(video_path)
    idx = 0
    saved = []
    while True:
        ret, frame = cap.read()
        if not ret:
            break
        if idx % step == 0:
            fname = f"frame_{idx:06d}.jpg"
            fpath = os.path.join(out_folder, fname)
            cv2.imwrite(fpath, frame)
            saved.append(fpath)
        idx += 1
    cap.release()
    return saved

# ---------- helper: make simple PDF ----------
def make_pdf(pdf_path, video_name, frames):
    c = canvas.Canvas(pdf_path, pagesize=A4)
    w, h = A4
    c.setFont("Helvetica-Bold", 16)
    c.drawString(40, h-40, f"Train Report for {video_name}")
    c.setFont("Helvetica", 12)
    c.drawString(40, h-70, f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    c.drawString(40, h-100, f"Total Frames Extracted: {len(frames)}")

    y = h - 150
    for f in frames[:N_FRAMES_PDF]:
        try:
            c.drawImage(f, 40, y-120, width=260, height=120, preserveAspectRatio=True)
        except:
            pass
        y -= 150
        if y < 100:
            c.showPage()
            y = h - 100
    c.save()

# ---------- main ----------
videos = [f for f in os.listdir(RAW_DIR) if f.lower().endswith(".mp4")]
print("Found videos:", videos)

for v in videos:
    vpath = os.path.join(RAW_DIR, v)
    vname = Path(v).stem
    out_folder = os.path.join(OUTPUT_DIR, vname)
    os.makedirs(out_folder, exist_ok=True)

    # extract frames
    frames = extract_frames(vpath, out_folder, step=FRAME_EVERY)
    print(f"Extracted {len(frames)} frames from {v}")

    # make PDF
    pdf_path = os.path.join(out_folder, f"Report_{vname}.pdf")
    make_pdf(pdf_path, vname, frames)
    print("PDF saved at:", pdf_path)

import shutil

shutil.make_archive("/content/Processed_Output", 'zip', "/content/Processed")

from google.colab import files
files.download("/content/Processed_Output.zip")

